name: PAMol
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.11.26=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - python=3.8.20=he870216_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - absl-py==0.15.0
    - annotated-types==0.7.0
    - appdirs==1.4.4
    - asttokens==3.0.0
    - astunparse==1.6.3
    - attrs==24.2.0
    - backcall==0.2.0
    - bel-resources==0.0.3
    - biopython==1.83
    - bioregistry==0.11.17
    - boto3==1.35.71
    - botocore==1.35.71
    - cachetools==5.5.0
    - certifi==2024.8.30
    - charset-normalizer==3.4.0
    - click==8.1.7
    - click-plugins==1.1.1
    - comm==0.2.2
    - contourpy==1.1.1
    - curies==0.7.10
    - cycler==0.12.1
    - debugpy==1.8.11
    - decorator==5.1.1
    - docker-pycreds==0.4.0
    - easydict==1.13
    - executing==2.1.0
    - filelock==3.16.1
    - flatbuffers==1.12
    - fonttools==4.55.3
    - gast==0.4.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - google-auth==2.36.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - greenlet==3.1.1
    - grpcio==1.34.1
    - h5py==3.1.0
    - humanize==4.10.0
    - idna==3.10
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - ipykernel==6.29.5
    - ipython==8.12.3
    - ipywidgets==8.1.5
    - jedi==0.19.2
    - jinja2==3.1.4
    - jmespath==1.0.1
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - jupyterlab-widgets==3.0.13
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.7
    - lmdb==1.5.1
    - loguru==0.7.2
    - markdown==3.7
    - markupsafe==2.1.5
    - matplotlib==3.6.0
    - matplotlib-inline==0.1.7
    - more-click==0.1.2
    - more-itertools==10.5.0
    - multisplitby==0.0.1
    - nest-asyncio==1.6.0
    - networkx==1.11
    - numpy==1.19.5
    - oauthlib==3.2.2
    - openbabel-wheel==3.1.1.20
    - opt-einsum==3.3.0
    - packaging==24.2
    - pandas==1.4.2
    - parso==0.8.4
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - pillow==10.4.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.3.6
    - prompt-toolkit==3.0.48
    - protobuf==3.20.3
    - psutil==6.1.0
    - psycopg2-binary==2.9.10
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pydantic==2.10.2
    - pydantic-core==2.27.1
    - pygments==2.18.0
    - pyparsing==3.1.4
    - pystow==0.5.6
    - python-dateutil==2.9.0.post0
    - pytrie==0.4.0
    - pytz==2024.2
    - pyyaml==6.0.2
    - pyzmq==26.2.0
    - ratelimit==2.2.1
    - rdkit==2023.9.5
    - referencing==0.35.1
    - requests==2.32.3
    - requests-file==2.1.0
    - requests-oauthlib==2.0.0
    - rpds-py==0.20.1
    - rsa==4.9
    - s3transfer==0.10.4
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - seaborn==0.12.0
    - sentry-sdk==2.19.0
    - setproctitle==1.3.4
    - six==1.15.0
    - smmap==5.0.1
    - sortedcontainers==2.4.0
    - sqlalchemy==1.1.15
    - stack-data==0.6.3
    - tabulate==0.9.0
    - tape-proteins==0.5
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6.2.2
    - tensorflow-estimator==2.5.0
    - tensorflow-gpu==2.5.0
    - termcolor==1.1.0
    - threadpoolctl==3.5.0
    - torch==1.12.1+cu116
    - torch-geometric==2.3.0
    - tornado==6.4.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - typing-extensions==3.7.4.3
    - urllib3==1.26.20
    - wandb==0.16.5
    - wcwidth==0.2.13
    - werkzeug==3.0.6
    - widgetsnbextension==4.0.13
    - wrapt==1.12.1
    - zipp==3.20.2

